# In this notebook we are going yo cover the most fundamental concepts of tensors using tensorflow

We are going to cover
* intro to tensors
* getting info from tensors
* manipulating tensors
* tensors and numpy
* using @tf functions(a way to speedup regular python functions)
* using GPU's with tensorflow


# Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matrix that has more than one dimension 
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
from numpy import float16
# Create another matrix
another_matrix = tf.constant([[10., 9.],
                             [3.,8.],
                             [1.,9.]], dtype= float16) # specify the data type with dtype parameter 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  9.],
       [ 3.,  8.],
       [ 1.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3


What we created so far:

* Scalar: a single number
* Vector: a number with direction 
* Matrix: a 2-dimension array of numbers
* Tensor: an n-dimensional array of numbers (n can be 0 to n) (a 0 dimensional tensor is a scalar and 1 dimensional tensor is a vector)

### Create tensors with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the same tensors with python variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([7,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
# Lets try change one of the elements in our changeable tensors
changeable_tensor[0] = 9
changeable_tensor

TypeError: ignored

In [ ]:
# Try .assign()
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
# Lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

## Creating Random Tensors
Random tensors are tensors of arbitary size using random numbers


In [ ]:
# create two random but the same tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (Helpful for when u want to shuffle ur data so that inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [1, 5]])

# Shuffle our non-shuffled tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed=19
not_shuffled = tf.constant([[10, 9],
                           [1, 4],
                           [1, 9]])

# Shuffle our non-shuffled tensor
shuffled = tf.random.shuffle(not_shuffled, seed=7)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 1,  9],
       [ 1,  4]], dtype=int32)>

### Other ways to make tensors

In [ ]:
# create a tensor with all ones
tf.ones([4,5])

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#  Create a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

#### The main differences between numpy arrays and tensorflow tensors is that tensors can be run on GPUs

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(6,2,2))
B= tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(6, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20]],
 
        [[21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting Information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimension tensors)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

### Indexing Tensors

#### Tensors can be indexed by python list 

In [ ]:
lis = [1,23,4,6]
lis[:2]

[1, 23]

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :, :]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2 = np.ones(shape=[2,3])
rank_2_tensor = tf.constant(rank_2, dtype=float16)
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
# Get last item of each row in a tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 1.], dtype=float16)>

In [ ]:
# Add in extra dimension in our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float16)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis =-1) # -1 means expand the final axis


<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float16)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis =1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 1, 3), dtype=float16, numpy=
array([[[1., 1., 1.]],

       [[1., 1., 1.]]], dtype=float16)>

### Manipulating Tensor/Tensor Operation

**Basic Operations**

`+`, `-`, `*`, `/` 





In [ ]:
# You can add values to a tensor using addition
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function
tf.multiply(tensor ,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning matrix multiplication is one of the most common operation

1. The inner dimension must match
2. The resulting matrix has shape of outer dimension

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with tensor operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# create a tensor of (3,2) 
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
Y = tf.constant([[7,8],
                  [9,10],
                 [10,11]
                 ])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [10, 11]], dtype=int32)>)

In [ ]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 10, 11]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  28,  31],
       [ 61,  64,  71],
       [ 95, 100, 111]], dtype=int32)>

In [ ]:
# Try matrix multiplication with transpos rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84,  93],
       [110, 122]], dtype=int32)>

Generally when performing matrix multiplication on two tensors and one of the tensors doesn't line up you will transpose one of the tensors to satisfy matrix multiplication. 

### Changing the datatype of a tensor 

In [ ]:
# create a new tensor with new data type (float32)
B = tf.constant([1.7, 4.9])
B.dtype

tf.float32

In [ ]:
C = tf.constant([2,9])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=  tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.9], dtype=float16)>

In [ ]:
C = tf.cast(C, dtype=tf.int16)
C

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 9], dtype=int16)>

### Aggregating Tensors

Aggregating Tensors: Condensing them from multiple values down to smaller amount values.

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
# Create a random tensor with values 0 to 100 with size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([30, 50, 86, 33, 25, 79, 11, 40, 65, 66, 16, 45, 22, 44, 64, 66, 32,
       79, 29, 43,  5,  2, 90, 84, 38,  1, 89, 55, 38, 92, 16, 55,  7, 63,
       91, 26, 28, 75, 38, 56, 22, 61, 41, 24,  5, 98, 89, 24, 58,  7])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# FInd the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [ ]:
# Find the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2303>

In [ ]:
# Find the Std of a tensor (We need to find tensorflow probability)

import tensorflow_probability as tfp
#tfp.stats.variance(E)
E = tf.cast(E, dtype=tf.float16)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=776.5>

In [ ]:
# Find the Std of a tensor (Both works without probability)
E = tf.cast(E, dtype=tf.float16)
#tfp.stats.stddev(E)
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=27.86>

### Find the Positional, Maximum and minimum


In [ ]:
### Create a new tensor for finding positional, minimum and maximum(Random seed equal asignment works)
tf.random.set_seed = 42
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.44606328, 0.32932448, 0.25765944, 0.5249958 , 0.4514755 ,
       0.2441982 , 0.28604472, 0.5966517 , 0.17625892, 0.54917276,
       0.08035088, 0.2864231 , 0.07153487, 0.97605085, 0.5724523 ,
       0.63616514, 0.70728934, 0.4239229 , 0.2961017 , 0.91227996,
       0.7024611 , 0.27057207, 0.5672935 , 0.24430704, 0.27744663,
       0.8883579 , 0.0092696 , 0.29345953, 0.3093568 , 0.79564583,
       0.0423491 , 0.8009803 , 0.8075365 , 0.34680188, 0.88289917,
       0.6291679 , 0.81240046, 0.16121757, 0.7565563 , 0.81906915,
       0.934541  , 0.7110677 , 0.43332517, 0.74078596, 0.78630555,
       0.56591725, 0.8317262 , 0.04803252, 0.636873  , 0.9310154 ],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [ ]:
# Finding the largest value in position 38 or the axes
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.97605085>

In [ ]:
# Getting the maximum value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.97605085>

In [ ]:
# Euqality checking
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Finding the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=26>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009269595>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009269595>

### Squeezing the tensor (Removing all single dimension in tensor)

In [ ]:
# Create a tensor to get started
tf.random.set_seed = 42
G = tf.constant(tf.random.uniform(shape = [50]), shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.00226176, 0.1260444 , 0.55983496, 0.14076507, 0.2723807 ,
          0.79459333, 0.02957249, 0.91927123, 0.3379439 , 0.06606627,
          0.2968613 , 0.38330495, 0.28827608, 0.53733647, 0.87201643,
          0.21540606, 0.99084485, 0.24047887, 0.11956322, 0.090868  ,
          0.3293246 , 0.8584757 , 0.62399364, 0.17529559, 0.4810617 ,
          0.5249435 , 0.91498613, 0.7648665 , 0.72459245, 0.11511564,
          0.08453202, 0.05096769, 0.32276654, 0.7683805 , 0.7110001 ,
          0.4782306 , 0.4759153 , 0.1154424 , 0.10302401, 0.3226061 ,
          0.9847479 , 0.8205445 , 0.10982323, 0.14990771, 0.22504413,
          0.20137143, 0.07326436, 0.981853  , 0.04522407, 0.01687837]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.00226176, 0.1260444 , 0.55983496, 0.14076507, 0.2723807 ,
       0.79459333, 0.02957249, 0.91927123, 0.3379439 , 0.06606627,
       0.2968613 , 0.38330495, 0.28827608, 0.53733647, 0.87201643,
       0.21540606, 0.99084485, 0.24047887, 0.11956322, 0.090868  ,
       0.3293246 , 0.8584757 , 0.62399364, 0.17529559, 0.4810617 ,
       0.5249435 , 0.91498613, 0.7648665 , 0.72459245, 0.11511564,
       0.08453202, 0.05096769, 0.32276654, 0.7683805 , 0.7110001 ,
       0.4782306 , 0.4759153 , 0.1154424 , 0.10302401, 0.3226061 ,
       0.9847479 , 0.8205445 , 0.10982323, 0.14990771, 0.22504413,
       0.20137143, 0.07326436, 0.981853  , 0.04522407, 0.01687837],
      dtype=float32)>

### One hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3]


In [ ]:
# One hot encode of our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom value for one hot encoding
tf.one_hot(some_list, depth=4, on_value="lol", off_value= "goodness gracious!!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'lol', b'goodness gracious!!', b'goodness gracious!!',
        b'goodness gracious!!'],
       [b'goodness gracious!!', b'lol', b'goodness gracious!!',
        b'goodness gracious!!'],
       [b'goodness gracious!!', b'goodness gracious!!', b'lol',
        b'goodness gracious!!'],
       [b'goodness gracious!!', b'goodness gracious!!',
        b'goodness gracious!!', b'lol']], dtype=object)>

### Squaring, Log and SQRT

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H = tf.cast(H, dtype=  tf.float16)
H

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float16)>

In [ ]:
# SQRT
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# LOG
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy

Tensorflow interacts beautifully with numpy arrays

In [ ]:
# Create a tensor directly form a numpy array
J = tf.constant(np.array([3.,2.,7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 2., 7.])>

In [ ]:
# Convert out tensor to numpy array
np.array(J), type(np.array(J))

(array([3., 2., 7.]), numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([3., 2., 7.]), numpy.ndarray)

In [ ]:
J.numpy()[0]

3.0

In [ ]:
# The default type of each are slightly different
K = tf.constant(np.array([1.,3.,5]))
L = tf.constant([1,3., 5])

K.dtype,L.dtype

(tf.float64, tf.float32)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Apr 27 06:13:51 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    30W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------